---
title: "Review Core Curriculum"
author: "Linli Zhou"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




#Reporting Items

1. For each term (fall/spring): # courses/ sections offered in each core segment
2. For each term (fall/spring): # enrollment (by transfer status) in each core segment
3. % of pass, C or better, and Withdrawal; Average GPA (and SD) of each courses
4. course-taking sequence

```{r core courses}
corecourse<-tibble(
"Writing I&II"<-c("WRT101","WRT102"),
"Math106"<-c("MATH106","MATH107","MATH116","MATH202","MATH203","MATH203","MATH205","MATH208","MATH209"),
"FYS103"<-c("FYS103","HON101"),
"Multidisciplinary"<-c("MDSC203", "HON205"),
"PHIL302"<-c("PHIL302"),
"Aesthetics & Creativity"<-c("ARTH107", "ARTS106", "ARTS126", "ARTS205", "ENG210", "ENG217", "ENG218", "ENG225", "MUS101", "MUS102", "MUS109", "MUS203", "PERF107", "PERF111","PERF202", "PERF203"),
"Global & Historical"<-c("HIST104"),
"Individuals & Society"<-c("SOC104","ANTH101", "CJ101", "COM103", "ENV101", "LS101", "PSYC101", "SOC101", "SOC102"),
"Scientific Inquiry & Problem Solving"<-c("BIO101", "BIO102", "BIO107", "BIO113", "CHEM105", "CHEM203", "ENV206", "ENV211", "ENV220", "MATH109", "PHYS111", "PHYS112", "SCI103", "SCI104", "SCI105", "SCI106", "SCI107", "SCI114", "SCI115", "SCI117", "SCI118", "SCI119"),
"Internship"<-c("BIO420","BUSS497","CHEM407","COM400","CJ443","CJ444","DSCI499","ED496","ED498","ED482","ED484","ED427","EXSC410","EXSC425","FASH415","FSCI407","GRAP400","HS415","HS425","HUM400","LS443","LS444"),
"Capstone"<-c("BIO430","BUSS440","CJ441","CJ442","COM495","DSCI409","ED494","ENG402","EXSC430","FASH427","FSCI480","GLBS401","GRAP404","HIST401","HS427","HUM419","HUM420","LS441","LS442","MATH399"))
#anything that has a KP(Knowledge Perspective) designation
```









