---
title: "CourseReqreuimentImpact"
author: "Linli Zhou"
date: "2022-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(stringr)
library(writexl)
library(RCurl)#web scrapping html
library(XML)#web scrapping html
library(rvest)#web scrapping html
```

# Set Up Data
```{r load data}
#which sheet
excel_sheets("/Users/linlizhou/Documents/LASELL/data/enrollment/All Course Requirements.xlsx")
#read data
data<-read_excel("/Users/linlizhou/Documents/LASELL/data/enrollment/All Course Requirements.xlsx",sheet = "Data")
```

```{r select major}
#remove mutated summary col 3-6; remove minors
dat.major<-data%>%select(-names(data)[3:6],-ends_with("Minor"))

#remove NA rows in section
dat.major<-dat.major[!is.na(dat.major$Section),]#removed last several NA rows, change from 941 to 935 row
```


# 43 Majors

## Accounting

```{r html-accounting}
#read html and parse it into R readable contents
pg<-htmlParse(getURL("https://www.lasell.edu/academics/academic-catalog-21-22/undergraduate-catalog-21-22/programs-of-study-/accounting-21-22.html"))
#look at all names and counts of names
summary(pg)
#read the table within html contents and save it as a tibble
crs.tbl<-readHTMLTable(pg,stringsAsFactors = FALSE)%>%as_tibble() #a tibble of 30 observation of 1 var

#make a course list
names(crs.tbl)="course" #rename tibble from NULL to "course" so that I can call it by its name without causing error
df<-crs.tbl$course#finally got a dataframe of 3 vars

#needs to confirm if the last item is blank, if yes, select the 1:length-1 for crs
crs<-df$`Course Code`[1:length(df$`Course Code`)-1]#character not a list; remove the last item -- which is a blank row
crs.df<-data.frame(Section=crs)%>%filter(!grepl("School",Section),!grepl("Core Courses",Section))#remove first two lables that separate all requried courese
#now we got the list of all html courses (with a label separator between required vs elective courses)
```

```{r append new courses using crs.df}
#inspect - filter out not in the dat.major courese and new those courese as new.crs.df; remove the last label patterns using filter grepl
new.crs.df<-crs.df%>%filter((crs.df$Section %in% dat.major$Section ) == FALSE)%>%filter(!grepl("Choose",Section))#we got a list of all new courses

#append new.df with dat.major
dat.major<-plyr::join_all(list(dat.major,new.crs.df),type = "full")#change from 935 to 947 with appended rows
```

```{r keep core course and recode using crs.df}
#investigate
dat.major%>%group_by(Accounting)%>%count()
#recode using case_when (new var= old var name)
dat.major<-
  dat.major%>%mutate(Accounting=case_when(
    Accounting=="C"~"Core",
    Section %in% crs.df$Section[1:21] ~"Required",
    Section %in% crs.df$Section[23:27] ~"Elective"))#%>%group_by(Accounting)%>%count()#check directly after mutate, before assign it to df
```

## Entrepreneurship

```{r html-Entrepreneurship}
#read html and parse it into R readable contents
pg<-read_html("https://www.lasell.edu/academics/academic-catalog-21-22/undergraduate-catalog-21-22/programs-of-study-/Entrepreneurship-21-22.html#tab-2")
#look at it (a list object that contains the tree-like structure)
pg
#search using nodes (html tags or css class) and print text
pg %>% html_nodes("body")%>%html_text()#indeed all contents of body
#search using css class as nodes
pg %>% html_nodes(".mp-modal")%>%html_text()#we must add a . before the class name
```


```{r find the right texts in html}
#read the table within html contents and save it as a tibble
crs.tbl<-pg %>% html_nodes(".mp-modal")%>%html_text()%>%as_tibble() #a tibble of 30 observation of 1 var

#make data frame with named col
crs.df<-data.frame(Section=crs.tbl$value)
#now we got the list of all html courses
```

```{r append new courses using crs.df}
#inspect - filter out not in the dat.major courese and new those courese as new.crs.df; remove the last label patterns using filter grepl
new.crs.df<-crs.df%>%filter((crs.df$Section %in% dat.major$Section ) == FALSE)

#append new.df with dat.major
dat.major<-plyr::join_all(list(dat.major,new.crs.df),type = "full")#change from 947 to 948 with appended rows BUSS407
```

```{r keep core course and recode using crs.df}
#investigate
dat.major%>%group_by(Entrepreneurship)%>%count()
#recode using case_when (new var= old var name)
dat.major<-
  dat.major%>%mutate(Entrepreneurship=case_when(
    Entrepreneurship=="C"~"Core",
    Section %in% crs.df$Section[1:18] ~"Required",
    Section %in% crs.df$Section[19:29] ~"Elective"))#%>%group_by(Entrepreneurship)%>%count()#check directly after mutate, before assign it to df
```

## Event Management

```{r html-`Event Management`}
#read html and parse it into R readable contents
pg<-read_html("https://www.lasell.edu/academics/academic-catalog-21-22/undergraduate-catalog-21-22/programs-of-study-/event-management21-22.html#tab-2")
#look at it (a list object that contains the tree-like structure)
pg
#search using css class as nodes
pg %>% html_nodes(".mp-modal")%>%html_text()#we must add a . before the class name
```


```{r find the right texts in html}
#read the table within html contents and save it as a tibble
crs.tbl<-pg %>% html_nodes(".mp-modal")%>%html_text()%>%as_tibble() #a tibble of 30 observation of 1 var

#make data frame with named col
crs.df<-data.frame(Section=crs.tbl$value)
#now we got the list of all html courses
```

```{r append new courses using crs.df}
#inspect - filter out not in the dat.major courese and new those courese as new.crs.df; remove the last label patterns using filter grepl
new.crs.df<-crs.df%>%filter((crs.df$Section %in% dat.major$Section ) == FALSE)

#append new.df with dat.major
dat.major<-plyr::join_all(list(dat.major,new.crs.df),type = "full")#no change 948
```

```{r keep core course and recode using crs.df}
#investigate
dat.major%>%group_by(`Event Management`)%>%count()
#recode using case_when (new var= old var name)
dat.major<-
  dat.major%>%mutate(`Event Management`=case_when(
    `Event Management`=="C"~"Core",
    Section %in% crs.df$Section[1:20] ~"Required",
    Section %in% crs.df$Section[21:35] ~"Elective"))#%>%group_by(`Event Management`)%>%count()#check directly after mutate, before assign it to df
```


## Business-Management

```{r html-`Business-Management`}
#read html and parse it into R readable contents
pg<-read_html("https://www.lasell.edu/academics/academic-catalog-21-22/undergraduate-catalog-21-22/programs-of-study-/business-management-21-22.html#tab-2")
#look at it (a list object that contains the tree-like structure)
pg
#search using css class as nodes
pg %>% html_nodes(".mp-modal")%>%html_text()#we must add a . before the class name
```


```{r find the right texts in html}
#read the table within html contents and save it as a tibble
crs.tbl<-pg %>% html_nodes(".mp-modal")%>%html_text()%>%as_tibble() #a tibble of 30 observation of 1 var

#make data frame with named col
crs.df<-data.frame(Section=crs.tbl$value)
#now we got the list of all html courses
```

```{r append new courses using crs.df}
#inspect - filter out not in the dat.major courese and new those courese as new.crs.df; remove the last label patterns using filter grepl
new.crs.df<-crs.df%>%filter((crs.df$Section %in% dat.major$Section ) == FALSE)

#append new.df with dat.major
dat.major<-plyr::join_all(list(dat.major,new.crs.df),type = "full")#no change 948
```

```{r keep core course and recode using crs.df}
#investigate
dat.major%>%group_by(`Business-Management`)%>%count()#non-existing major
#recode using case_when (new var= old var name)
dat.major<-
  dat.major%>%mutate(`Business-Management`=case_when(
   # `Business-Management`=="C"~"Core", #hide for not-existing major
    Section %in% crs.df$Section[1:18] ~"Required",
    Section %in% crs.df$Section[19:length(crs.df$Section)] ~"Elective"))#%>%group_by(`Business-Management`)%>%count()#check directly after mutate, before assign it to df
```