---
title: "2022 First Impression Survey Results"
author: ""
date: "Sep 20-30, 2022"
output:
  bookdown::word_document2:
    fig_caption: yes
    reference_docx: "/Users/linlizhou/Documents/Rprojects/lasell.report.docx"
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, warning=FALSE, message=FALSE) #show only results
source("/Users/linlizhou/Documents/Rprojects/IR-Projects/theme_source.R") #run code from saved theme and library
```

```{r load and clean data}
#read data
fis<-read_csv("/Volumes/Faculty_Staff_Shares$/IR/Surveys/Lasell Internal/First Impressions/2022 Fall/20221013124928-SurveyExport.csv")
```


```{r match ppid from allstu22 for fis}
#fis email rename
fis<-fis%>%
  rename(email=`Please provide your Lasell email address. This information is needed for research purposes. Your personal information will be kept confidential and will not appear on any report. `)

#fis email.short
fis<-fis%>%
  mutate(email.short=gsub("@lasell.edu","",fis$email),#remove extra to keep all values the same format
         email.short=str_to_lower(email.short))%>%  #lower case
  select(-email)#to avoid too many cols get merged



#backup data email
allstu<-read_excel("/Volumes/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Fall/Fall 2022 UG Backup Data Report.xlsx")

#select 2022 cohort and vars
allstu22<-allstu%>%
  filter(`Cohort Id`=="2022")%>%#this year's students
  select(`People Code Id`, Name,`Lasell email`,
         `Transfer YN`,`Res/Comm`,Gender,Ethnicity,`FT/PT`)%>%#select all usable vars
  rename(gender=Gender)#to avoid join by "Gender"

#create email.short
allstu22<-allstu22%>%
  mutate(email.short=gsub("@lasell.edu","",allstu22$`Lasell email`),#remove extra to match fis emails
         email.short=str_to_lower(email.short))%>%#keep lower case format
  select(-`Lasell email`)#avoid too many cols get merged


#merge
fis<-left_join(fis,allstu22,by="email.short")#all fis with a valid email will have a ppid and names now
#check: sum(is.na(fis$`People Code Id`));sum(is.na(fis$Name))#only 16 do not find a matched ppid/name
```


```{r select vars and SAVE fis.s}
#select: remove starter cols
fis.s<-fis%>%select(-(`Response ID`:Source),-(`Invite Custom Field 2`:Gender))%>%#removed 54 cols
  janitor::remove_empty(c("rows", "cols"))#remove empty rows/cols (including header has to be NA), removed 1 rows

#remove NA cols: nothing get removed
fis.s<-fis.s[ , colSums(is.na(fis.s)) < nrow(fis.s)] #sum each col's # of NA rows, as long as not all rows are NA then select them 

#check: names(fis)[names(fis)%in%names(fis.s)==FALSE]
```


```{r one ppid col}
#rename headers
#ppid
#check: sum(is.na(fis.s$`Invite Custom Field 1`));sum(is.na(fis.s$`People Code Id`))#148vs15
fis.s<-fis.s%>%mutate(ppid=if_else(!is.na(`Invite Custom Field 1`),#if settled by field then field
                            `Invite Custom Field 1`,`People Code Id`))%>%#if not settled, then matched id
  select(-`Invite Custom Field 1`,-`People Code Id`)
#check: sum(is.na(fis.s$ppid))#14 without ppid
```


```{r rename cols and SAVE xlsx}
#look at the survey instruction and lapply(fis.s, unique) to do this
fis.s<-fis.s%>%rename(
  RCstatus=`Which of the following describes your status for the 2022 fall semester?`,
#satisfaction 0-6 scale  
  satis.activity=`Campus-wide programs and activities (virtual or in-person)?:Please tell us how satisfied you are with…`,
  satis.activity.cm=`Comment or example::Please tell us how satisfied you are with…...58`,
  
  satis.overallcourse=`Your courses overall so far?:Please tell us how satisfied you are with…`,
  satis.majorcourse=`Your courses within your major so far? (If you are an undeclared major, please leave blank):Please tell us how satisfied you are with…`,
  satis.course.cm=`Comment or example::Please tell us how satisfied you are with…...61`,
  
  satis.acchallenge=`The degree of academic challenge in your courses?:Please tell us how satisfied you are with…`,
  satis.acchallenge.cm=`Comment or example::Please tell us how satisfied you are with…...63`,

  satis.accommit=`Other students' commitment to their studies?:Please tell us how satisfied you are with…`,
  satis.accommit.cm=`Comment or example::Please tell us how satisfied you are with…...65`,
  
  satis.foodav=`Food service availability on campus?:Please tell us how satisfied you are with…`,
  satis.foodav.cm=`Comment or example::Please tell us how satisfied you are with…...67`,
  
  satis.residstaff=`Residential Life staff?:Please tell us how satisfied you are with…`,
  satis.residstaff.cm=`Comment or example::Please tell us how satisfied you are with…...69`,
  
  satis.residhall=`Your living situation in the residence halls?:Please tell us how satisfied you are with…`,
  satis.residhall.cm=`Comment or example::Please tell us how satisfied you are with…...71`,

#connection 0-6 scale  
  connect.faculty=`Faculty?:How connected do you feel to…`,
  connect.faculty.cm=`Comment or example::How connected do you feel to…...73`,
  
  connect.stu=`Other students?:How connected do you feel to…`,
  connect.stu.cm=`Comment or example::How connected do you feel to…...75`,

#emphasis question: 4 text scale  
  emphasize.acsupport=`Using learning support services (tutoring services, writing center, etc):Based on your experience so far, how much does Lasell University emphasize the following?`,
  emphasize.socoppo=`Providing opportunities to be involved socially:Based on your experience so far, how much does Lasell University emphasize the following?`,
  emphasize.campactivity=`Attending campus activities and events (virtual or in-person):Based on your experience so far, how much does Lasell University emphasize the following?`,
  emphasize.issueevents=`Attending events that address important social, economic, or political issues:Based on your experience so far, how much does Lasell University emphasize the following?`,

#satisfaction 0-6 scale
  service.aac=`Academic Achievement Center:Please tell us how satisfied you are with…`,
  service.aac.cm=`Comment or Example::Please tell us how satisfied you are with…...81`,

  service.classtech=`Classroom Technology and Computer Labs:Please tell us how satisfied you are with…`,
  service.classtech.cm=`Comment or Example::Please tell us how satisfied you are with…...83`,

  service.counseling=`Counseling Center (Located at 18 Maple Terrace):Please tell us how satisfied you are with…`,
  service.counseling.cm=`Comment or Example::Please tell us how satisfied you are with…...85`,

  service.acadvisor=`Your academic advisor:Please tell us how satisfied you are with…`,
  service.acadvisor.cm=`Comment or Example::Please tell us how satisfied you are with…...87`,

  service.health=`Health Services (Located in Edwards Student Center):Please tell us how satisfied you are with…`,
  service.health.cm=`Comment or Example::Please tell us how satisfied you are with…...89`,

  service.techhealp=`Technology Help Desk:Please tell us how satisfied you are with…`,
  service.techhealp.cm=`Comment or Example::Please tell us how satisfied you are with…...91`,

  service.shuttle=`Lasell Shuttle:Please tell us how satisfied you are with…`,
  service.shuttle.cm=`Comment or Example::Please tell us how satisfied you are with…...93`,

  service.other=`Please type the service(s) in to the box (i.e. vending, mailroom, washing/drying etc.):Please provide feedback on any other services on campus we have not mentioned in the previous questions.`,
  service.other.cm=`Feedback::Please provide feedback on any other services on campus we have not mentioned in the previous questions.`,

#academic 0-6 scale
  meetacexpect=`Is the college meeting your expectations in terms of academic experience?:Please tell us a little bit about what you think of Lasell's academics.`,
  meetacexpect.cm=`Comment or example::Please tell us a little bit about what you think of Lasell's academics.`,

  faculty.orgmaterial=`Present material in a well-organized way?:How often do your faculty…`,
  faculty.explain=`Make good use of examples and illustrations to explain difficult points?:How often do your faculty…`,
  faculty.prep=`Come to class well prepared?:How often do your faculty…`,
  faculty.command=`Have a good command of what they are teaching?:How often do your faculty…`,

#outside class 0-6 agreement
  interact.outside=`I have had a positive interaction with at least one Lasell faculty or staff member outside of class.:How much do you agree…`,
  interact.cm=`How have you been able to effectively interact with others in the Lasell community in a safe manner so far this semester?`,
  interact.difficulty=`What are the difficulties you’re facing when interacting with others within the Lasell community this semester?`)

#write.xlsx(fis.s,"/Volumes/Faculty_Staff_Shares$/IR/Surveys/Lasell Internal/First Impressions/2022 Fall/raw_renamed.xlsx")
```

## Respondents

```{r respondents vs overall SAVE full df}
#approach 1
#data merge full
fis.s<-fis.s%>%mutate(RespondentOverall="Respondents")
allstu22<-allstu22%>%mutate(RespondentOverall="All First-Year Students")%>%rename(ppid=`People Code Id`)
fulldf<-full_join(fis.s,allstu22)

#response rate
num.response=fulldf%>%filter(RespondentOverall=="Respondents")%>%nrow()
num.overall=fulldf%>%filter(RespondentOverall=="All First-Year Students")%>%nrow()
response_rate=formattable::percent(num.response/num.overall,digits=0)

#approach 2
#allstu22.s<-allstu22%>%select(-RespondentOverall)
#allstu22.s<-allstu22.s%>%mutate(ResAll=
 #                       if_else(ppid%in%fis.s$ppid,#if id is one of the same survey id 
  #                      "Respond","Not Respond"))
#check: allstu22.s%>%count(ResAll) #314 person, 195 responded, 177 have ppid, 18 no ppid
```


```{r one RCstatus col in fulldf}
fulldf<-fulldf%>%mutate(Res_Com=if_else(!is.na(RCstatus),#if settled by RC then RC
          RCstatus,`Res/Comm`))%>%#if not settled, then res/com from allstu
  select(-RCstatus,-`Res/Comm`)%>%
  mutate(RCstatus=if_else(Res_Com=="R","Resident",
                          if_else(Res_Com=="C","Commuter",Res_Com)))%>%
  select(-Res_Com)
  
#check: fulldf.t%>%count(RCstatus)
```

```{r recode race in fulldf}
fulldf<-fulldf%>%mutate(Ethnicity=if_else(is.na(Ethnicity),"Race and Ethnicity Unknown",Ethnicity))%>%
  mutate(Ethnicity=if_else(Ethnicity=="Race and Ethnicity Unknown","Unknown",Ethnicity))%>%
  mutate(Ethnicity=if_else(Ethnicity=="Two or more Races","Multi-races",Ethnicity))%>%
  mutate(Ethnicity=if_else(Ethnicity=="Non Resident Alien","International",Ethnicity))%>%
  mutate(Ethnicity=if_else(Ethnicity=="Native Hawaiian or Other Pacific Islander","Native",Ethnicity))%>%
  mutate(Ethnicity=if_else(Ethnicity=="Black or African American","Black",Ethnicity))
```




```{r ResAll.waffle}
#response rate
ResAll.waffle<-fulldf%>%group_by(RespondentOverall)%>%summarise(cnt=n())%>%mutate(prt=round(cnt/sum(cnt)*100,digits = 0))%>%
ggplot(aes(values = prt, fill=RespondentOverall)) +
  geom_waffle(color="white",flip = TRUE)+
   labs(title=str_wrap(paste0(response_rate," Response Rate"),40),#, " (",num.response, " out of ", num.overall,")"),40),#80 is a full line length
       x="",y="",fill="", 40)+
       #subtitle=str_wrap("Data collection: Sep 20-30, 2022"),40)+ #shows bottom right
  theme_lz()+
    scale_y_discrete(labels=c("Respondents","All First-year"))+
  scale_fill_manual(values = c("#6C6F70","#69b3e7"))#fill legend labels=c(""),name="")
 # geom_text(aes(x = prt, y=RespondentOverall, label=paste0(RespondentOverall,": ",prt)),color="white",position = position_dodge(0.9),hjust=1)

#response rate
#ResAll.number<-fulldf%>%count(RespondentOverall)%>%
#ggplot(aes(x = n, y=RespondentOverall, fill=RespondentOverall)) +
#  geom_col()+
#  labs(title=str_wrap(paste0(response_rate," Response Rate"),40),#, " (",num.response, " out of ", num.overall,")"),40),#80 is a full line length
#       x="",y="",fill="", 40)+
       #subtitle=str_wrap("Data collection: Sep 20-30, 2022"),40)+ #shows bottom right
#  theme_lz()+theme(legend.position = "none")+
    #scale_y_discrete(labels=c("Respondents","All First-year"))+
#  scale_fill_manual(values = c("#69b3e7","#6C6F70"))+#fill legend labels=c(""),name="")
#  geom_text(aes(label=paste0(RespondentOverall,": ",n)),color="white",position = position_dodge(0.9),hjust=1)
```


```{r respondent res.com figure, fig.height=3}
#background info: gender & ethnicity, FT/PT & Transfer, RC
#RC
ResAll.rcstatus<-fulldf%>%group_by(RespondentOverall,RCstatus)%>%summarise(cnt=n())%>%
  mutate(prt=formattable::percent(cnt/sum(cnt),digits=0))%>%
  
ggplot(aes(x = prt, fill=RespondentOverall, y=RCstatus)) +
  geom_bar(stat="identity",position = position_dodge())+
  labs(title=str_wrap("Resident vs Commuters Composition",40),#80 is a full line length
       x="",y="",fill="", 
    #   subtitle=str_wrap(paste0("6% Residents and 94% Commuters"),40), 
       caption="")+ #shows bottom right
  theme_lz()+
  theme(axis.text.y = element_text())+
    scale_y_discrete(labels=c("Commuters","Residents"))+
  geom_text(aes(label=paste0(prt)),size=3,position = position_dodge(0.9),hjust=0.5)+#, " ", RCstatus," among ",RespondentOverall
  scale_fill_manual(values = c("#6C6F70","#69b3e7"))#fill legend labels=c(""),name="")
```




```{r respondent gender.ethnicity figure, fig.height=3}
#background info: gender & ethnicity
ResAll.gdeth<-fulldf%>%group_by(Ethnicity,gender)%>%summarise(cnt=n())%>%
  mutate(prt=formattable::percent(cnt/sum(cnt),digits=0))%>%
  
ggplot(aes(x = prt, fill=gender, y=Ethnicity)) +
  geom_bar(stat="identity",position = position_dodge())+
  labs(title=str_wrap("Gender & Ethnicity Composition",40),#80 is a full line length
       x="",y="",fill="", 
       caption="")+ #shows bottom right
  theme_lz()+
  theme(axis.text.y = element_text())+
  #  scale_y_discrete(labels=c("Commuters","Residents"))+
  geom_text(aes(label=paste0(prt)),size=3,position = position_dodge(0.9),hjust=0.5)+#, " ", RCstatus," among ",RespondentOverall
  #scale_fill_manual(values = c("#6C6F70","#69b3e7"))#fill legend labels=c(""),name="")
  facet_wrap(RespondentOverall,ncol=2)
```

```{r respondent_figures,include=TRUE,fig.height=2,fig.width=6}
gridExtra::grid.arrange(ResAll.waffle,ResAll.rcstatus, ncol=2)
ResAll.gdeth
```













