---
title: "NSSE"
author: "Linli Zhou"
date: "2022-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, warning=FALSE, message=FALSE, fig.align = "center") #display code along with its results
library(haven)
library(readxl)
library(tidyverse)
library(writexl)
library(ggrepel)
```

```{r setup color, include=FALSE}
library(ggplot2)

mycolors<-c("#13294b","#5c88da","#69b3e7","#fcb53b","#6C6F70","#641F45")
scale_color_manual(values=mycolors)

theme_lz <- function(){ 
    font <- "Helvetica"   #assign font family up front
    theme_minimal() %+replace%    #replace elements already strips axis lines, 
    theme(
      panel.grid.major = element_blank(),    #strip major gridlines
      panel.grid.minor = element_blank(),    #strip minor gridlines
      plot.title = element_text(family = font, size = 9, face = 'bold',hjust = 0.5, vjust = 2),
      axis.title = element_blank(), 
      axis.text = element_blank(), 
      axis.text.x = element_text(family = font, size = 9, margin = margin(t=5,b=10)),
      axis.ticks = element_blank(),          #strip axis ticks
      
      legend.title = element_text(family = font, size=9),
      legend.text = element_blank(),
      legend.position="none",
      
      strip.text = element_text(family = font, size = 9, margin = margin(t=5,b=10)),#move up is + 1
      strip.background = element_blank()
    )}
```


## Purpose

This project compared NSSE result from freshmen in 2018 who become senior in 2022. I did a merge-and-match first, then visualize each matched students' change in terms of NSSE survey results.

```{r load data}
#2022 data
nsse22.sav<-read_sav("/Users/linlizhou/Documents/LASELL/data/NSSE_report/data/NSSE22 Data (Lasell).sav")
#save as excel for better readability
write_xlsx(nsse22.sav,"/Users/linlizhou/Documents/LASELL/data/NSSE_report/data/NSSE22 Data (Lasell).xlsx")
#using tibble from excel
nsse22<-read_excel("/Users/linlizhou/Documents/LASELL/data/NSSE_report/data/NSSE22 Data (Lasell).xlsx")

#2018 data
nsse18.sav<-read_sav("/Users/linlizhou/Documents/LASELL/data/NSSE_report/data/NSSE18 Data (Lasell College).sav")
#save as excel for better readability
write_xlsx(nsse18.sav,"/Users/linlizhou/Documents/LASELL/data/NSSE_report/data/NSSE18 Data (Lasell).xlsx")
#using tibble from excel
nsse18<-read_excel("/Users/linlizhou/Documents/LASELL/data/NSSE_report/data/NSSE18 Data (Lasell).xlsx")
```

```{r find vars of interest}
#find pcid
grep("[Ii][Dd]",names(nsse22),value=TRUE)#find student id
nsse22$studentid[1:5]

#find class
grep("class",names(nsse22),value=TRUE)#find student id
nsse22$IRclass[1:5]

#find codebook
lable<-sjlabelled::get_label(nsse22.sav)
lable["IRclass"]#Institution-reported: Class level


#select variable of interest in nsse22 (select and rename using lable from sav)
nsse22.s<-nsse22%>%select("PCID"="studentid","Class"="IRclass","Higher-Order Learning"="HO", "Reflective and Integrative Learning"="RI","Learning Strategies"="LS","Quantitative Reasoning"="QR","Collaborative Learning"="CL","Discussions with Diverse Others"="DD","Student-Faculty Interaction"="SF","Effective Teaching Practices"="ET","Quality of Interactions"="QI","Supportive Environment"="SE")%>%
  mutate(Year="2022")#prep for merge to distinguish data from 2022


#do the same for nsse18 (since they have the same structure each year)#only studentID in 18 is different from studentid in 22
nsse18.s<-nsse18%>%select("PCID"="studentID","Class"="IRclass","Higher-Order Learning"="HO", "Reflective and Integrative Learning"="RI","Learning Strategies"="LS","Quantitative Reasoning"="QR","Collaborative Learning"="CL","Discussions with Diverse Others"="DD","Student-Faculty Interaction"="SF","Effective Teaching Practices"="ET","Quality of Interactions"="QI","Supportive Environment"="SE")%>%
  mutate(Year="2018")#prep for merge to distinguish data from 2018

```

```{r no match}
ns1822<-inner_join(x=nsse22.s,y=nsse18.s,by="PCID",suffix=c(".18",".22"))#zero match of PCID
ns1822<-merge(x=nsse22.s,y=nsse18.s,by="PCID",suffix=c(".18",".22"))#zero match of PCID
```

```{r general comparison using full dataset}
ns1822<-full_join(x=nsse22.s,y=nsse18.s)#383=212+171
```

```{r first year 18-22}
ns1822%>%group_by(Year,Class)%>%summarise(score=mean(`Higher-Order Learning`,na.rm=T))%>%mutate(prt=score/sum(score))%>%
  ggplot(aes(x=factor(Class),y=score,fill=factor(Class)))+#make class a factor to display as categorical var properly
  geom_bar(stat="identity",position = position_dodge(),width=.8)+
  geom_text_repel(aes(label=round(score,digits=0)),color="black",size=4,position= position_nudge())+
  facet_wrap(~Year)+
  theme_lz()+
  scale_fill_manual(values = c(mycolors[2],mycolors[1]), name="Class")
```































