---
title: "CommonDataset_report"
format: pdf
editor: visual
---

```{r set up}
source("/Users/linlizhou/Documents/Rprojects/IR-Projects/theme_source.R")
```

# CDS-I Class Size

```{r load_secsize}
secsize<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/Common Data Set/2022-2023/datafiles/Course Count FA'22_cleanCDS-I.xlsx")
#for convience of reporting
secsize<-secsize%>%mutate(size=factor(size,levels =c("2-9","10-19","20-29","30-39") ))


```

```{r report_sec.size}
#section
secsize%>%filter(type=="section")%>%
  filter(!is.na(size))%>%#remove 1 individual enrolled classes
  count(size)%>%
  pivot_wider(names_from = size, values_from = n)#convnience to report

#check type: secsize%>%count(type)
#subsection: including lab and recitation
secsize%>%filter(type%in%c("lab","recitation"))%>%
  filter(!is.na(size))%>%#remove 1 individual enrolled classes
  count(size)%>%
  pivot_wider(names_from = size, values_from = n)#convnience to report

#compared to 2021-22 data: looks similar
# compared to raw(cleaned data): results are the same
```

# CDS-F Fall Enrollment: state, res/com, age (degseek vs ftfy)

```{r load_fallenroll}
#degsk<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/Common Data Set/2022-2023/datafiles/Fall 2022 UG Backup Data Report_cleanCDS-F.xlsx")
fallenroll<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/Common Data Set/2022-2023/datafiles/Fall 2022 UG Backup Data Report_cleanCDS-FandB.xlsx")
```

```{r report_degsk.state}
#important vars are admit_region, fyft and others
#admit region
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  count(ADMIT_REGION)%>%
  filter(ADMIT_REGION!="intl",#exclude international from numerator and denominator
         !is.na(ADMIT_REGION))%>%#remove NA from discussion
  mutate(prt=n/sum(n)*100)%>%
  filter(ADMIT_REGION=="other states")#only report out of state prt
```

```{r report_degsk.res.com}
#recoding live on vs off campus
fallenroll$`Res/Comm`<-recode(fallenroll$`Res/Comm`,C="off campus",R="on campus")
#for convinience of reporting
fallenroll<-fallenroll%>%mutate(`Res/Comm`=factor(`Res/Comm`,
                          levels = c("on campus","off campus")))

#report
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  count(`Res/Comm`)%>%
  mutate(prt=n/sum(n)*100)
```

```{r report_degsk.age}
#age 25 or older
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  mutate(age.gp=if_else(Age>=25,">=25","<25"))%>%
  count(age.gp)%>%
  filter(!is.na(age.gp))%>%#remove the one NA
  mutate(prt=n/sum(n)*100)%>%
  filter(age.gp==">=25")#only report 25 or older
#check with raw data: 1186 <25; 1235 has age value; 96% is < 25


#avg age of full time students
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  filter(`FT/PT`=="FT")%>%#full time students
  summarise(mn=mean(Age,na.rm=TRUE))

#avg age of all students
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  summarise(mn=mean(Age,na.rm=TRUE))
```

```{r report_ftfy}
#admit region
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  filter(fyft=="Y")%>%#only first time/non-transfer/complt first year/new students
  count(ADMIT_REGION)%>%
  filter(ADMIT_REGION!="intl",#exclude international from numerator and denominator
         !is.na(ADMIT_REGION))%>%#remove NA from discussion
  mutate(prt=n/sum(n)*100)%>%
  filter(ADMIT_REGION=="other states")#only report out of state prt

#live on vs off campus
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  filter(fyft=="Y")%>%#only fyft students
  count(`Res/Comm`)%>%
  mutate(prt=n/sum(n)*100)

#age
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  filter(fyft=="Y")%>%#only fyft students
  mutate(age.gp=if_else(Age>=25,">=25","<25"))%>%
  count(age.gp)%>%
  filter(!is.na(age.gp))%>%#remove the one NA
  mutate(prt=n/sum(n)*100)%>%
  filter(age.gp==">=25")#only report 25 or older
#check with raw data: 315 <25; 324 has age value; 97% is < 25

#avg age of full time students
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  filter(fyft=="Y")%>%#only fyft students
  filter(`FT/PT`=="FT")%>%#full time students
  summarise(mn=mean(Age,na.rm=TRUE))

#avg age of all students
fallenroll%>%filter(degreeseek=="Y")%>%#degree seeking students
  filter(fyft=="Y")%>%#only fyft students
  summarise(mn=mean(Age,na.rm=TRUE))
```

# CDS-B2 Fall Enrollment: race

```{r factorize_eth}
#for convnience of reporting
#check: fallenroll%>%count(Ethnicity)
fallenroll<-fallenroll%>%mutate(Ethnicity=factor(Ethnicity,
            levels = c("Non Resident Alien","Hispanic","Black or African American",
                       "White","Asian","Native Hawaiian or Other Pacific Islander",
                       "Two or more Races","Race and Ethnicity Unknown")))
```

```{r report_allenroll.race}
fallenroll%>%
  count(Ethnicity)
```

```{r report_degsk.race}
#report degsk race
fallenroll%>%filter(degreeseek=="Y")%>%
  count(Ethnicity)
```

```{r report_ftfy.degsk.race}
fallenroll%>%filter(degreeseek=="Y",#degree seeking students
                    fyft=="Y")%>%#first time first year students
  count(Ethnicity)
```

# CDS-J Complete by CIP

```{r load_ipedscomplete}
complete<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/Common Data Set/2022-2023/datafiles/Complete.with.Ethnicity_age.eric.editted_cleanCDS-J.xlsx")

#for convinience of reporting: complete<-complete%>%mutate(degree_awarded=factor(degree_awarded, levels = c("bachelor","associate","certificates"))) #, turns out can't change order in pivot_wider
```

```{r report_cip.prt}
#check: complete%>%count(Degree,degree_awarded)
complete%>%
  filter(degree_awarded%in%c("bachelor's degree","associate degree"))%>%
  #only report UG (bachelor's certificate, associate, and bachelor's); 
  #no master/certificate: current certificates are all postbachelor
  group_by(cip.2g,degree_awarded)%>%summarise(cnt=n())%>%
  ungroup()%>%#so that it's not prt within the second subgroup
  mutate(prt=round(cnt/sum(cnt),digits = 4))%>%select(-cnt)%>%
  pivot_wider(names_from = degree_awarded,values_from = prt, values_fill = 0)%>%
  View()#for copy paste
```

# CDS-B3 Complete by Degree

```{r report_degree.cnt}
#check mapping: complete%>%count(Degree,degree_awarded)
complete%>%count(degree_awarded)
```
