---
title: "CommonDataset"
author: "Linli Zhou"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
source("/Users/linlizhou/Documents/Rprojects/IR-Projects/theme_source.R")
#any enrollment is fall 2022; 
#any completion is academic year 2021-2022

#"c&d-admission; #h-financialaid; g-business office (we can fill out this year2022); #i-2)faculty-eric turner/aca affairs 3)once get faculty we calculate ratio; 
#i-1)class size: registar#the rest we can do (a,b,e,f,j) e/f-might be a question for someone else#b(UG part)/j can complete now"
```

#CDS-I Class Size

```{r load reg crs data}
# 22Fall UG class size (including online classes)
# section: course for credit (exclude individual instruction/ intern/practicums/ independent study), count cross-reg only once
# sub-section: supplementary (e.g. lab, recitation, discussion session) to a course for credit and non-individual (defined above)

#data source: registar's office already have a clean course file: removed duplicated cross-registration, removed individual courses
crstabs<-excel_sheets("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Fall/Course Count FA'22.xlsx")
## results:"Course Count"     "Recitations"      "Labs"             "Directed Studies"
sec.crscnt<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Fall/Course Count FA'22.xlsx",sheet = crstabs[1])
subsec.recit<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Fall/Course Count FA'22.xlsx",sheet =crstabs[2])
subsec.lab<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Fall/Course Count FA'22.xlsx",sheet = crstabs[3])
```


```{r clean section subsection}
#clean data
sec.crscnt<-sec.crscnt%>%
  #class size of each course
  mutate(size=case_when(`Current Enrollment`>=2 & `Current Enrollment`<=9 ~ "2-9",
                        `Current Enrollment`>=10 & `Current Enrollment`<=19 ~ "10-19",
                        `Current Enrollment`>=20 & `Current Enrollment`<=29 ~ "20-29",
                        `Current Enrollment`>=30 & `Current Enrollment`<=39 ~ "30-39",
                        `Current Enrollment`>=40 & `Current Enrollment`<=49 ~ "40-49",
                        `Current Enrollment`>=50 & `Current Enrollment`<=99 ~ "50-99",
                        `Current Enrollment`>=100~ "100+"))

#distinguish two types of subsec
subsec.lab<-subsec.lab%>%mutate(type="lab")
subsec.recit<-subsec.recit%>%mutate(type="recitation")
#merge the two types of subsection together
subsec<-full_join(subsec.lab,subsec.recit)%>%
  #class size of each subsection
  mutate(size=case_when(`Current Enrollment`>=2 & `Current Enrollment`<=9 ~ "2-9",
                        `Current Enrollment`>=10 & `Current Enrollment`<=19 ~ "10-19",
                        `Current Enrollment`>=20 & `Current Enrollment`<=29 ~ "20-29",
                        `Current Enrollment`>=30 & `Current Enrollment`<=39 ~ "30-39",
                        `Current Enrollment`>=40 & `Current Enrollment`<=49 ~ "40-49",
                        `Current Enrollment`>=50 & `Current Enrollment`<=99 ~ "50-99",
                        `Current Enrollment`>=100~ "100+"))

#merge to one file
sec.crscnt<-sec.crscnt%>%mutate(type="section")
#merge sec with subsec
classsize<-full_join(sec.crscnt, subsec)
```


```{r save classsize}
#save the two sheets
#load raw
wb<-loadWorkbook("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/Common Data Set/2022-2023/datafiles/Course Count FA'22.xlsx")
#add new sheet "clean" on raw
addWorksheet(wb,"clean")
#assign classsize as clean sheet
writeData(wb,"clean", x = classsize)

#check names: names(wb)
#set order of sheets
worksheetOrder(wb) <- c(5,1,2,3,4)
#save all in a new file
saveWorkbook(wb,"/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/Common Data Set/2022-2023/datafiles/Course Count FA'22_clean.xlsx",overwrite = TRUE)
```


#CDS-F

```{r load UGbackup}
#find list of "degree-seeking" UG, and "first-time, first-year degree-seeking" UG, both enrolled in 22Fall (include FT&PT)
enrolled22fa<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Fall/Fall 2022 UG Backup Data Report.xlsx")#The one in IR Reports is an unofficial file
#check each cols: lapply(enrolled22fa[,9:28], unique)
```


```{r degseek}
#list of "degree-seeking" UG
degseek<-enrolled22fa%>%filter(Degree!="NON", #"BS", "AA", "BA", "CER"
                               Program!="LV")#exclude lasell villiage: Any Lasell Village student is non-matriculated, it does not matter what the indication in the degree column is.  
#check each cols: lapply(degseek[,9:28], unique)
```

```{r explore degseek vars: LV - hardcode to non-matric}
#explore:
#LV is non matriculated or AA: Any Lasell Village student is non-matriculated, it does not matter what the indication in the degree column is.  
enrolled22fa%>%filter(Program=="LV")%>%count(Degree)
#non matriculated are non-matric and lasell village: enrolled22fa%>%filter(Degree=="NON")%>%count(Program,Curriculum)
```


```{r degseek.ftfy}
#list of "first-time, first-year degree-seeking" UG
degseek.ftfy<-degseek%>%filter(
  `Transfer YN`=="N",#not transfered-in (of all class level)->first time is at lasell
  !str_detect(Curriculum, "[Cc]ompletion"), # not a completion program -- which is a non-trditional transfer student
  `College Attend`=="NEW")#new/ the first actual year in the institution
```

```{r understand classLevel and newCollegeAttend}
#class level: not "real year in school", but coded based on cum credits (SO>30,JR>60,SR>90), : degseek%>%group_by(`Class level`)%>%count(`Cum Credits`,sort = TRUE)

#college attend new: "new/first actual/literal year at Lasell" (instead of returning Lasell)
degseek%>%filter(`College Attend`=="NEW")%>%count(`Transfer YN`)# transfer in, but new to lasell
```


```{r understand CohortId and Matric Year}
#matric year and cohort IDs for degseek students:
enrolled22fa%>%filter(Degree!="NON", Program!="LV")%>%#degseek students
  count(`Matric Year`,`Cohort Id`)%>%#map matric and cohort
  mutate(`Matric Year`=ymd(`Matric Year`,truncated = 2),
         `Cohort Id`=ymd(`Cohort Id`,truncated = 2))%>%#format as date
  mutate(diff=`Matric Year`-`Cohort Id`)%>%#diff between dates
  mutate(diff=round(as.numeric(diff)/365,digits=0))%>%##reformat as diff in years
  filter(diff!=0 | is.na(diff))%>%arrange(diff)%>%#see those inconsistency between matric and cohort
  mutate(`Matric Year`=format(`Matric Year`,format="%Y"),
         `Cohort Id`=format(`Cohort Id`,format="%Y"))#only care about year

#comments from eric: 

#cohort ID  (e.g. 2022, 2022 PT): first time, new (college attend column, i.e. first actual year at Lasell) in 2022, degree seeking students
enrolled22fa%>%count(`Cohort Id`)# 2022 CER means: students in UG Surgical Technology, a 1-year certificate program
#cohort ID interger (e.g. 2022) means full time: degseek%>%filter(`Cohort Id`=="2022")%>%count(`FT/PT`)
enrolled22fa%>%filter(!is.na(`Cohort Id`))%>%count(Degree)#only BA, BS first time degree seeking

#NA cohort ID: transfer (not first time), bachelor's completion (transfer students looking to complete a Bachelor's degree that they have already started), non-matrics (not degree-seeking), workforce development (not degree-seeking)
enrolled22fa%>%filter(is.na(`Cohort Id`))%>%count(Degree)#non-matric, transfer students in BA/BS, Lasell Village students in AA, 
#and CER surgical tech from previous years (2022 CER has a cohort ID)
enrolled22fa%>%filter(Degree=="CER")%>%count(`Transfer YN`,Curriculum,`College Attend`)

#Matric year: the first year in which the student was in a matriculated (matriculated is the same as degree-seeking) program.
#For those with differences between the 2 codes, we would have to look them up individually to see what is going on, I don't think it's necessarily straight forward.
```

```{r verify degseek.ftfy with CohortId}
#should be the same as cohort Id= 2022 ...(first time, new in 2022, degree seeking students)

#two filters and not exactly cohort Id= 2022 ...: have two extra NA
degseek%>%filter(`Transfer YN`=="N", `College Attend`=="NEW",)%>%count(`Cohort Id`)# the NA are from bachelor's completion program(non-traditional transfer student)

#three filters and exactly cohort Id= 2022 ...
degseek%>%filter(`Transfer YN`=="N",!str_detect(Curriculum, "[Cc]ompletion"), `College Attend`=="NEW",)%>%count(`Cohort Id`)#remove curriculum contains completion (not first time students), then removed NA

#so it's correct to use the three filters to identify first time first year students
```

```{r combine degseek and degseek.fyft as one df}
degseek<-degseek%>%mutate(fyft=if_else(
  degseek$`People Code Id`%in%degseek.ftfy$`People Code Id`,
  "Y","N"))#check:%>%count(fyft)
#check:fyft "Y" is same with nrow(degseek.ftfy) #324 first time new/first year students

#check no duplication: degseek%>%group_by(`People Code Id`)%>%count()%>%group_by(n)%>%count()#1236degseek students
```

```{r merge dmt-out of state}

```


