---
title: "Enrollment report"
author: "Linli Zhou"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyverse)
library(writexl)
library(openxlsx)
library(lubridate)
```

```{r load enrollment data}
#ENROLLMENT (REGISTRAR BACKUP) 07/01/2021-06/30-2022

##2021 Summer II
ug21sum2<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2021 Summer/Summer II/Undergraduate Backup Data  Report 21SUII.xlsx")
gd21sum2<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2021 Summer/Summer II/GR/Graduate Backup Data  Report.xlsx")
##2021 Fall
ug21fa<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2021 Fall/FA2021 Undergraduate Backup Data  Report.xlsx")
g21fa<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2021 Fall/Grad/main.SI.S2 GR backup data.xlsx")
##2022 Winter
ug22wi<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Winter/WI2022 UG Backup Data  Report.xlsx")
gd22wi<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Winter/Grad Backup data WI22.xlsx")
##2022 Spring
ug22sp<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Spring/UG/Spring 2022 UG Backup Data.xlsx")
gd22sp<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Spring/Grad/Graduate SP22 Final Backup Data  Report.xlsx")
##2022 Summer Main&I
ug22sum.main.1<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Summer/Main and I/SUM22 SES1 and Main UG Backup Data  Report - 2022-06-02T080930.592.xlsx")
gd22sum.main.1<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Registrar Reports/2022 Summer/Main and I/SUM22 MainSES1-Graduate Backup Data  Report (23).xlsx")
```


```{r clean data header}
####################clean data headers
#investigate names 1)view df 2)find no headers and tackling those headers
#tackling ug21sum2
names(ug21sum2)<-ug21sum2[3,]#header is the third row
n<-nrow(ug21sum2)#prep the length
ug21sum2<-ug21sum2[4:n,]#select from 4th row to the end
ug21sum2<-ug21sum2%>%select(-`NA`)#remove NA col
#since no need to merge all, no need to care about each and every col
##compare larger col df to smaller col df; and select from larger col to see what's not exist
##names(ug21fa)%in%names(ug21sum2)
##names(ug21fa)[names(ug21fa) %in% names(ug21sum2) == "FALSE"]#no Age; SCHOOL that in larger data but not in smaller data

#tackling ug22wi
names(ug22wi)<-ug22wi[3,]#header is the third row
n<-nrow(ug22wi)#prep the length
ug22wi<-ug22wi[4:n,]#select from 4th row to the end
ug22wi<-ug22wi%>%select(-`NA`)#remove NA col

#tackling gd22sum.main.1
names(gd22sum.main.1)<-gd22sum.main.1[3,]#header is the third row
n<-nrow(gd22sum.main.1)#prep the length
gd22sum.main.1<-gd22sum.main.1[4:n,]#select from 4th row to the end
gd22sum.main.1<-gd22sum.main.1%>%select(-`NA`)#remove NA col

#tackling g21fa
names(g21fa)<-g21fa[6,]#header is the 6th row
n<-nrow(g21fa)#prep the length
g21fa<-g21fa[7:n,]#select from 7th row to the end
g21fa<-g21fa%>%select(-`NA`)#remove NA col

#tackling gd21sum2
names(gd21sum2)<-gd21sum2[6,]#header is the 6th row
n<-nrow(gd21sum2)#prep the length
gd21sum2<-gd21sum2[7:n,]#select from 7th row to the end
gd21sum2<-gd21sum2%>%select(-`NA`)#remove NA col

#tackling gd22wi
names(gd22wi)<-gd22wi[6,]#header is the 6th row
n<-nrow(gd22wi)#prep the length
gd22wi<-gd22wi[7:n,]#select from 7th row to the end
gd22wi<-gd22wi%>%select(-`NA`)#remove NA col
```


```{r ug}
ug1<-ug21fa%>%select(`People Code Id`,`gov id`,`FT/PT`,Degree,`Transfer YN`,`College Attend`,Ethnicity,Gender,`Term Credits`,`Cum Credits`,Curriculum,`Birth Date`)%>%
  mutate(Level="UG",term="21fall")#mutate identification col

ug2<-ug21sum2%>%select(`People Code Id`,`gov id`,`FT/PT`,Degree,`Transfer YN`,`College Attend`,Ethnicity,Gender,`Term Credits`,`Cum Credits`,Curriculum,`Birth Date`)%>%
  mutate(Level="UG",term="21summer2")

ug3<-ug22sp%>%select(`People Code Id`,`gov id`,`FT/PT`,Degree,`Transfer YN`,`College Attend`,Ethnicity,Gender,`Term Credits`,`Cum Credits`,Curriculum,`Birth Date`)%>%
  mutate(Level="UG",term="22spring")

ug4<-ug22sum.main.1%>%select(`People Code Id`,`gov id`,`FT/PT`,Degree,`Transfer YN`,`College Attend`,Ethnicity,Gender,`Term Credits`,`Cum Credits`,Curriculum,`Birth Date`)%>%
  mutate(Level="UG",term="22summer.1main")

ug5<-ug22wi%>%select(`People Code Id`,`gov id`,`FT/PT`,Degree,`Transfer YN`,`College Attend`,Ethnicity,Gender,`Term Credits`,`Cum Credits`,Curriculum,`Birth Date`)%>%
  mutate(Level="UG",term="22winter")

#check selected vars
#sapply(list(ug1,ug2,ug3,ug4,ug5), function(x) ncol(x))#same 14

#merge to one ug dataset
ug<-plyr::join_all(list(ug1,ug2,ug3,ug4,ug5),type="full")%>%
  unique()%>%#remove rows that has exact same value across all columns
  rename(Program=Curriculum,`New Ret Term YN`=`College Attend`, ppid=`People Code Id`)%>%#rename for ug-gd consistency
  mutate(degree.t=case_when(Degree %in% c("NON","Non Matriculated")~"Non-degree",Degree!="NON" & Degree!="Non Matriculated" ~"Degree-seeking"))%>%
  select(-Degree)#create degree.t (and remove old)

#check
#sapply(list(ug1,ug2,ug3,ug4,ug5), function(x) nrow(x))%>%sum()#2935
#nrow(ug.ipeds)#match="first" #2935
#ncol(ug.ipeds)#14
#names(ug.ipeds)

```


```{r gd}
gd1<-g21fa%>%select(`People Code Id`,`gov id`,`Class level`,Gender,`FT/PT`,Ethnicity,`Term Credits`,`Cum Credits`,Degree,`Birth Date`,`New Ret Term YN`,`Transfer YN`)%>%
  mutate(Level="GD",term="21fall")#mutate identification col

gd2<-gd21sum2%>%select(`People Code Id`,`gov id`,`Class level`,Gender,`FT/PT`,Ethnicity,`Term Credits`,`Cum Credits`,Degree,`Birth Date`,`New Ret Term YN`,`Transfer YN`)%>%
  mutate(Level="GD",term="21summer2")

gd3<-gd22sp%>%select(`People Code Id`,`gov id`,`Class level`,Gender,`FT/PT`,Ethnicity,`Term Credits`,`Cum Credits`,Degree,`Birth Date`,`New Ret Term YN`,`Transfer YN`)%>%
  mutate(Level="GD",term="22spring")

gd4<-gd22sum.main.1%>%select(`People Code Id`,`gov id`,`Class level`,Gender,`FT/PT`,Ethnicity,`Term Credits`,`Cum Credits`,Degree,`Birth Date`,`New Ret Term YN`,`Transfer YN`)%>%
  mutate(Level="GD",term="22summer.1main")

gd5<-gd22wi%>%select(`People Code Id`,`gov id`,`Class level`,Gender,`FT/PT`,Ethnicity,`Term Credits`,`Cum Credits`,Degree,`Birth Date`,`New Ret Term YN`,`Transfer YN`)%>%
  mutate(Level="GD",term="22winter")

#check selected vars: compare to ug, do not have transfer, college status, and cum credit
#sapply(list(gd1,gd2,gd3,gd4,gd5), function(x) ncol(x))#same 14

#merge to one
gd<-plyr::join_all(list(gd1,gd2,gd3,gd4,gd5),type="full")%>%
  unique()%>%#remove rows that has exact same value across all columns
  rename(Program=Degree, ppid=`People Code Id`)%>%#renmae for ug-gd consistency
  mutate(degree.t=case_when(`Class level`!="GR"~"Non-degree",`Class level`=="GR" ~"Degree-seeking"))%>%
  select(-`Class level`)#create degree.t (and remove old)
 
#check
#sapply(list(gd1,gd2,gd3,gd4,gd5), function(x) nrow(x))%>%sum()#1513
#nrow(gd.ipeds)#match="first" #1512, removed 1 duplicated (across all values)
#ncol(gd.ipeds)
#names(gd.ipeds)%in%names(ug.ipeds)%>%sum()#14 all same
```


```{r ug.gd}
#merge ug.ipeds and gd ipeds
ug.gd<-plyr::join_all(list(ug,gd),type="full")%>%#4447 rows
  unique()%>%janitor::remove_empty(c("rows", "cols"))%>%#remove all-NA rows/cols!! 4443 rows
  filter(!is.na(ppid))#4422 row
#check
#sapply(list(ug.ipeds,gd.ipeds), function(x) nrow(x))%>%sum()#4447 rows
```


```{r ug.gd clean class and recode}
#str(ug.gd)
#ls<-ug.gd%>%group_by(Program)%>%count();View(ls)#no NA
#ug.gd[is.na(ug.gd$`Cum Credits`),]#a lot of NAs, all comes from UG 21 fall!
#ug.gd[is.na(ug.gd$`Birth Date`),]#find many, come from different file
ug.gd<-ug.gd%>%mutate(`FT/PT`=factor(`FT/PT`),
                      `Transfer YN`=factor(`Transfer YN`,labels =c("Transfer","Non-transfer"),levels = c("Y","N")),
                      
                      #"no" college status="new", "yes" college status="return"
                      `New Ret Term YN`=case_when(`New Ret Term YN`=="N"~"new",`New Ret Term YN`=="NEW"~"new",`New Ret Term YN`=="Y"~"return",`New Ret Term YN`=="RET"~"return",`New Ret Term YN`=="RETS"~"return"),
                      `New Ret Term YN`=factor(`New Ret Term YN`,levels = c("new","return")),
                      
                      Ethnicity=if_else(Ethnicity=="Non Resident Alien/International","Non Resident Alien",Ethnicity),
                      Ethnicity=factor(Ethnicity, levels=c("Non Resident Alien","Hispanic","American Indian or Alaska Native","Asian","Black or African American","White","Two or more Races","Race and Ethnicity Unknown")),
                      Gender=factor(Gender,levels = c("M","F","U")),
                      
                      `Term Credits`=as.numeric(`Term Credits`),
                      `Cum Credits`=as.numeric(`Cum Credits`),
                      `Birth Date`=mdy(`Birth Date`),
                      
                      Level=factor(Level,levels = c("UG","GD")),
                      term=factor(term,levels = c("21summer2","21fall","22winter","22spring","22summer.1main")),
                      degree.t=factor(degree.t))
#all cols are either factor (with correct values and orders), numeric, or stay as character (id without NA)

#write.xlsx(ug.gd,file="/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/ug.gd_21-22.xlsx")
```

# DETERMINE IN ORDER: determined by whatever value in fall, if enrolled in fall, then spring..winter..summer..

```{r consistent FT/PT Attend}
#FT/PT: determined by students' first full term (eric: of the academic year)

#whatever fall value
sts.fall<-ug.gd%>%mutate(status=if_else(term=="21fall",as.character(`FT/PT`),"No fall"))%>%
  arrange(ppid)%>%filter(status%in%c("FT","PT"))#only keep the settled

#not in fall, then determine by spring FT/PT
sts.spring<-ug.gd%>%filter(! ppid%in% sts.fall$ppid)%>%#only care those not-settled
  mutate(status=if_else(term=="22spring",as.character(`FT/PT`),"No spring"))%>%
  arrange(ppid)%>%filter(status%in%c("FT","PT"))#only keep the newly settled

#not in fall&spring, then determine by winter FT/PT
sts.winter<-ug.gd%>%filter(! ppid%in% c(sts.fall$ppid,sts.spring$ppid))%>%
  mutate(status=if_else(term=="22winter",as.character(`FT/PT`),"No winter"))%>%
  arrange(ppid)%>%filter(status%in%c("FT","PT"))

#not in fall&spring&winter, then determine by summer2 FT/PT  
sts.summer2<-ug.gd%>%filter(! ppid%in% c(sts.fall$ppid, sts.spring$ppid, sts.winter$ppid))%>%#only care those not-settled (after three settled cohorts)
  mutate(status=if_else(term=="21summer2",as.character(`FT/PT`),"No sum2"))%>%
  arrange(ppid)%>%filter(status%in%c("FT","PT"))

#not in fall&spring&winter&summer2, then determine by summer1 FT/PT
sts.summer1<-ug.gd%>%filter(! ppid%in% c(sts.fall$ppid, sts.spring$ppid, sts.winter$ppid, sts.summer2$ppid))%>%#filter out four settled cohort
  mutate(status=if_else(term=="22summer.1main",as.character(`FT/PT`),"No sum1"))%>%
  arrange(ppid)%>%filter(status%in%c("FT","PT"))

#mutate all settled (unique ids)
sts<-plyr::join_all(list(sts.fall,sts.spring,sts.summer2,sts.summer1,sts.winter),type ="full" )%>% unique()%>%arrange(ppid)%>%
  select(ppid,status)#select only relevant #2057

#left join all-uniqueid's-status to ug.gd
ug.gd<-plyr::join_all(list(ug.gd,sts),type="left")%>%unique()%>%arrange(ppid)%>%#4422
  select(-`FT/PT`)#status is the new FT/PT
```


```{r consistent NewRet}
#if enrolled in fall, then whatever FALL TERM new/ret values
ret.fall<-ug.gd%>%
  mutate(NewRet=if_else(term=="21fall",as.character(`New Ret Term YN`),"No fall"))%>%
  filter(NewRet%in%c("new","return"))%>%arrange(ppid)#either new or return of fall would be settled

#if not enrolled in fall but spring: determine by spring
ret.spring<-ug.gd%>%filter(! ppid%in% ret.fall$ppid)%>%#if not has a fall term
  mutate(NewRet=if_else(term=="22spring",as.character(`New Ret Term YN`),"No spring"))%>%
  arrange(ppid)%>%filter(NewRet%in%c("new","return"))#either new or return of spring would be settled

#if not in fall&spring at all, determine by winter
ret.winter<-ug.gd%>%filter(! ppid%in% c(ret.fall$ppid, ret.spring$ppid))%>%
  mutate(NewRet=if_else(term=="22winter",as.character(`New Ret Term YN`),"No winter"))%>%
  arrange(ppid)%>%filter(NewRet%in%c("new","return"))#either new or return of winter would be settled

#if not in fall&spring&winter at all, determine by summer2
ret.summer2<-ug.gd%>% filter(! ppid%in% c(ret.fall$ppid, ret.spring$ppid, ret.winter$ppid))%>%#if do not show up in fall&spring&winter
  mutate(NewRet=if_else(term=="21summer2",as.character(`New Ret Term YN`),"No sum2"))%>%
  arrange(ppid)%>%filter(NewRet%in%c("new","return"))#either new or return of sum2 would be settled

#if not in fall&spring&winter&summer2 at all, determine by summer1
ret.summer1<-ug.gd%>%filter(! ppid%in% c(ret.fall$ppid, ret.spring$ppid, ret.winter$ppid, ret.summer2$ppid))%>%
  mutate(NewRet=if_else(term=="22summer.1main",as.character(`New Ret Term YN`),"No sum1"))%>%#if do not show up in fall&spring&winter&sum2
  arrange(ppid)%>%filter(NewRet%in%c("new","return"))#either new or return of fall would be settled

#merge all settled (filtered unique ids from each term)
ret<-plyr::join_all(list(ret.fall,ret.spring,ret.summer2,ret.summer1,ret.winter),type ="full" )%>% unique()%>%arrange(ppid)%>%select(ppid,NewRet)#select what's needed 2057
 
#left join settledRetNew to ug.gd
ug.gd<-plyr::join_all(list(ug.gd,ret),type="left")%>%unique()%>%arrange(ppid)%>%#4422
  select(-`New Ret Term YN`)#select what's needed
```

# ONE DOMINATE: any degree is degree, any transfer is transfer

```{r consistent degree.t}
#degree: any of the term is degree-seeking then they are
#level: any of degree-seeking level
deg.s<-ug.gd%>%group_by(ppid,degree.t)%>%
  summarize(cnt=n())%>%#unique for ppid&degree.t
  mutate(degree.c=if_else(degree.t=="Degree-seeking",as.character(degree.t),"non"))%>%
  arrange(ppid)%>%filter(degree.c=="Degree-seeking")#keep any degree-seeking

#for ppid with not any degree-seeking
deg.n<-ug.gd%>%filter(! ppid%in% deg.s$ppid)%>%
  group_by(ppid,degree.t)%>%summarize(cnt=n())%>%
  mutate(degree.c="Non-degree")#all not settled with deg.s will be non

#merge settled deg
deg<-plyr::join_all(list(deg.s,deg.n),type ="full" )%>% 
  select(ppid,degree.c)%>%unique()%>%arrange(ppid)#2057

ug.gd<-plyr::join_all(list(ug.gd,deg),type="left")%>%
  select(-degree.t)%>%
  unique()%>%arrange(ppid)#4422
```


```{r level consistency}
#if determined by the time of admission level status
#dtm21fa<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Datamart Files/Test Run of Data Mart/Fall 2021/Table_Test_Run_Fall_Main_Ses1_Ses2_Sept_28_2021.xlsx")%>%filter(ENROLL_SEP_DESC=="Enrolled")

#dmt21fa%>%group_by(PROGRAM_1)%>%count()#only undergrad data

#any non-degree should not have a UG/GD status
lev.n<-ug.gd%>%filter(degree.c=="Non-degree")%>%
  mutate(level.c="Non-degree")%>%
  filter(level.c=="Non-degree")#keep only settled

#for degree-seeking, they either are UG/GD
#for one with both UG/GD level (conflict): anyone with UG are UG
lev.u<-ug.gd%>%filter(! ppid%in% c(lev.n$ppid))%>%#only taking about deg students
  mutate(level.c=if_else(Level=="UG","UG","non"))%>%
  arrange(ppid)%>%filter(level.c=="UG")%>%unique()#keep UG

#for ppid with not any degree-seeking
lev.g<-ug.gd%>% filter(! ppid%in% c(lev.u$ppid,lev.n$ppid))%>%#for any not settled
  mutate(level.c="GD")%>%unique()#all not settled with lev.s will be GD

#merge settled  lev
lev<-plyr::join_all(list(lev.n,lev.u,lev.g),type ="full" )%>%
  select(ppid,level.c)%>%unique()%>%arrange(ppid)#only what we needed, 2057
    
#left join unique-level to ug.gd
ug.gd<-plyr::join_all(list(ug.gd, lev),type="left")%>%unique()%>%arrange(ppid)%>%
  select(-Level,-degree.c)#only what we needed, 4422; do not need degree-seeking any more, because that will be determined by level
```


```{r consistent transfer}
#degree: any of the term is transfer then they are
tran.s<-ug.gd%>%group_by(ppid,`Transfer YN`)%>%
  summarize(cnt=n())%>%#unique for ppid&`Transfer YN`
  mutate(transfer=if_else(`Transfer YN`=="Transfer",as.character(`Transfer YN`),"non"))%>%arrange(ppid)%>%
  filter(transfer=="Transfer")#keep any degree-seeking

#for ppid with not any degree-seeking
tran.n<-ug.gd%>%filter(! ppid%in% tran.s$ppid)%>%
  group_by(ppid,`Transfer YN`)%>%summarize(cnt=n())%>%
  mutate(transfer="Non-transfer")#all not settled with tran.s will be non

#merge settled tran
tran<-plyr::join_all(list(tran.s,tran.n),type ="full" )%>% 
  select(ppid,transfer)%>%
 unique()%>%arrange(ppid)#2057

ug.gd<-plyr::join_all(list(ug.gd,tran),type="left")%>%
  select(-`Transfer YN`)%>%
  unique()%>%arrange(ppid)#4422
```

## AGGREGATE term to total credit - we only care about total
```{r credit by term wider, then merge total}
#ppid has different term and level
dup.id<-ug.gd %>% group_by(ppid,term) %>% #for each unique id,
  summarise(n_per_key=n()) %>% # count time of appearance
  arrange(desc(n_per_key))%>%filter(n_per_key>1)
  #ungroup %>% #release ppid back to original data
  #count(n_per_key)#count how many time each n_per_key appeared
ug.gd%>%filter(ppid==dup.id$ppid)
#one may take credit from ug and gd classes
ug.gd%>%group_by(ppid)%>%summarise(tot.credit=sum(`Term Credits`))

#replace NA to 0
ug.gd$`21fall`[is.na(ug.gd$`21fall`)]<-0
ug.gd$`22spring`[is.na(ug.gd$`22spring`)]<-0
ug.gd$`22summer.1main`[is.na(ug.gd$`22summer.1main`)]<-0
ug.gd$`21summer2`[is.na(ug.gd$`21summer2`)]<-0
ug.gd$`22winter`[is.na(ug.gd$`22winter`)]<-0

#Calculate total credit adding all terms
ug.gd<-ug.gd%>%mutate(credit.year=`21fall`+`22spring`+`22summer.1main`+`21summer2`+`22winter`)%>%
  select(-c(`21fall`,`22spring`,`22summer.1main`,`21summer2`,`22winter`))%>%arrange(ppid)%>%
  unique()#2089

ug.gd%>%distinct(ppid)#2057
###investigate duplicated ppid: it's b/c degree.t and level
#dup.id<-ug.gd[duplicated(ug.gd$ppid),]
#ug.gd[ug.gd$ppid %in% dup.id$ppid,]%>%arrange(ppid)
```

```{r}
ug.gd<-ug.gd%>%
  pivot_wider(names_from = Level,values_from = credit.year)%>%
  arrange(ppid)%>%
  unique()%>%janitor::remove_empty(c("rows","cols"))#2090

ug.gd$UG[is.na(ug.gd$UG)]<-0
ug.gd$GD[is.na(ug.gd$GD)]<-0

lv.ug<-ug.gd%>%group_by(ppid)%>%
  mutate(level=if_else(UG>0,"UG","na"))%>%arrange(ppid)%>%
  filter(level!="na")

lv.gd<-ug.gd%>%group_by(ppid)%>%
  filter(! ppid%in% lv.ug$ppid)%>%
   mutate(level=if_else(GD>0,"GD","na"))%>%arrange(ppid)%>%
  filter(level!="na")

lv<-plyr::join_all(list(lv.ug,lv.gd),type ="full" )%>% 
  select(ppid,level)%>%
 unique()%>%arrange(ppid)#2057

ug.gd<-plyr::join_all(list(ug.gd,lv),type="left")%>%mutate(credit.tot=UG+GD)%>%
  select(-UG,-GD)%>%
  unique()%>%arrange(ppid)#2061
```




```{r ipeds data}
########################################################################################
####################################################################################
################## IPEDS 12-month enrollment (due 2022 Oct 19)########
########################################################################################
#remove not needed cols
ipeds<-ug.gd%>%select(-`Cum Credits`,-Program,-`gov id`,-`Birth Date`)%>%
  unique()%>%arrange(ppid)#4422

###investigate duplicated ppid: it's b/c FT/PT, new/return, term credits, term
#dup.id<-ipeds[duplicated(ipeds$ppid),]
#ipeds[ipeds$ppid %in% dup.id$ppid,]%>%arrange(ppid)
```

```{r ipeds reporting}
#####################################################################################
#####################12-month Unduplicated Count by Race/Ethnicity and Gender########
             
#Full-time Undergraduate Students:MEN
##########DEGREE: FIRST TIME (College Attend=NEW)
##report first-time student in DEGREE-SEEKING column of the MEN table of UG
t1<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="FT",Gender=="M",degree.t=="Degree-seeking",`College Attend`=="NEW")%>%
  group_by(Ethnicity,.drop = FALSE)%>%summarise(firsttime=n())

##########DEGREE&NON FIRST TIME: TRANSFER VS RETURNING in "Transfer YN"
## focusing on return student, whether they are transfer or not
t2<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="FT",Gender=="M",degree.t=="Degree-seeking", `College Attend`=="RET")%>%
  group_by(`Transfer YN`,Ethnicity,.drop = FALSE)%>%count()%>%
  #transferY&N side by side
  pivot_wider(names_from = `Transfer YN`,values_from =  n, names_glue = paste0("Transfer","{`Transfer YN`}_{.value}"))

##########NON DEGREE
#report NON-DEGREE column
t3<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="FT",Gender=="M",degree.t=="Non-degree")%>%
  group_by(Ethnicity)%>%summarize(nondegree=n())

t<-plyr::join_all(list(t1,t2,t3),type="full",match="first")
t[is.na(t)]<-0
View(t)

#Full-time Undergraduate Students:WOMEN
##########DEGREE: FIRST TIME (College Attend=NEW)
##report first-time student in DEGREE-SEEKING column of the MEN table of UG
t1<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="FT",Gender=="F",degree.t=="Degree-seeking",`College Attend`=="NEW")%>%
  group_by(Ethnicity,.drop = FALSE)%>%summarise(firsttime=n())

##########DEGREE&NON FIRST TIME: TRANSFER VS RETURNING in "Transfer YN"
## focusing on return student, whether they are transfer or not
t2<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="FT",Gender=="F",degree.t=="Degree-seeking", `College Attend`=="RET")%>%
  group_by(`Transfer YN`,Ethnicity,.drop = FALSE)%>%count()%>%
  #transferY&N side by side
  pivot_wider(names_from = `Transfer YN`,values_from =  n, names_glue = paste0("Transfer","{`Transfer YN`}_{.value}"))

##########NON DEGREE
#report NON-DEGREE column
t3<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="FT",Gender=="F",degree.t=="Non-degree")%>%
  group_by(Ethnicity)%>%summarize(nondegree=n())

t<-plyr::join_all(list(t1,t2,t3),type="full",match="first")
t[is.na(t)]<-0
View(t)

#Part-time Undergraduate Students:MEN
##########DEGREE: FIRST TIME (College Attend=NEW)
##report first-time student in DEGREE-SEEKING column of the MEN table of UG
t1<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="PT",Gender=="M",degree.t=="Degree-seeking",`College Attend`=="NEW")%>%
  group_by(Ethnicity,.drop = FALSE)%>%summarise(firsttime=n())

##########DEGREE&NON FIRST TIME: TRANSFER VS RETURNING in "Transfer YN"
## focusing on return student, whether they are transfer or not
t2<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="PT",Gender=="M",degree.t=="Degree-seeking", `College Attend`=="RET")%>%
  group_by(`Transfer YN`,Ethnicity,.drop = FALSE)%>%count()%>%
  #transferY&N side by side
  pivot_wider(names_from = `Transfer YN`,values_from =  n, names_glue = paste0("Transfer","{`Transfer YN`}_{.value}"))

##########NON DEGREE
#report NON-DEGREE column
t3<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="PT",Gender=="M",degree.t=="Non-degree")%>%
  group_by(Ethnicity)%>%summarize(nondegree=n())

t<-plyr::join_all(list(t1,t2,t3),type="full",match="first")#%>%as.data.frame()#have to convert to df for is.na step
t[is.na(t)]<-0
View(t)


#Part-time Undergraduate Students:WOMEN
##########DEGREE: FIRST TIME (College Attend=NEW)
##report first-time student in DEGREE-SEEKING column of the MEN table of UG
t1<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="PT",Gender=="F",degree.t=="Degree-seeking",`College Attend`=="NEW")%>%
  group_by(Ethnicity,.drop = FALSE)%>%summarise(firsttime=n())

##########DEGREE&NON FIRST TIME: TRANSFER VS RETURNING in "Transfer YN"
## focusing on return student, whether they are transfer or not
t2<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="PT",Gender=="F",degree.t=="Degree-seeking", `College Attend`=="RET")%>%
  group_by(`Transfer YN`,Ethnicity,.drop = FALSE)%>%count()%>%
  #transferY&N side by side
  pivot_wider(names_from = `Transfer YN`,values_from =  n, names_glue = paste0("Transfer","{`Transfer YN`}_{.value}"))

##########NON DEGREE
#report NON-DEGREE column
t3<-ug.gd%>%filter(Level=="UG")%>%filter(`FT/PT`=="PT",Gender=="F",degree.t=="Non-degree")%>%
  group_by(Ethnicity)%>%summarize(nondegree=n())

t<-plyr::join_all(list(t1,t2,t3),type="full",match="first")#%>%as.data.frame()#have to convert to df for is.na step
t[is.na(t)]<-0
View(t)

#GD MEN
##report MEN's ethnicity by gender
t<-ug.gd%>%filter(Level=="GD")%>%filter(Gender=="M")%>%group_by(Ethnicity,`FT/PT`,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = `FT/PT`, values_from = n)
t$FT[is.na(t$FT)]<-0
t$PT[is.na(t$PT)]<-0
View(t)

#GD WOMEN
##report WOMEN's ethnicity by gender
t<-ug.gd%>%filter(Level=="GD")%>%filter(Gender=="F")%>%group_by(Ethnicity,`FT/PT`,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = `FT/PT`, values_from = n)
t$FT[is.na(t$FT)]<-0
t$PT[is.na(t$PT)]<-0
View(t)

#GENDER UNKNOWN
#UG unknown
ug.gd%>%filter(Level=="UG")%>%group_by(Gender)%>%count()#31
#GD unknown
ug.gd%>%filter(Level=="GD")%>%group_by(Gender)%>%count()#2
#Another gender blank - no value as another gender




#august 21  december 21 may 22
#ask linda's official file + report manager
#ba/bs 

####distance education: student info by course file // no option student courses file -- long to wide: the section type col to multiple cols, each contain one type of section format
####
####us_rent_income %>% pivot_wider(names_from = variable, values_from = mutated_countof1_eachrow,values_fill = 0)
```

