---
title: "IPEDScomplete-cached"
author: "Linli Zhou"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)#echo is codes
```

```{r load r package}
library(readxl)
library(dplyr)
library(plyr)#for join_all
library(writexl)
library(lubridate)
library(stringr)
```

```{r CACHED select var from annual, cache=TRUE}
#####direclty use Graduation Term Snapshot which contains all cols (PCID,level,degree,major,gradd,race,gender) I wanted####
#read  data (from report manager-IR-Graduation Term Snapshot)
#AY21-22
grad21sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/21sum.csv")
grad21f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/21f.csv")
grad22spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/22spr.csv")
#AY20-21
grad20sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/20sum.csv")
grad20f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/20f.csv")
grad21spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/21spr.csv")
#AY19-20
grad19sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/19sum.csv")
grad19f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/19f.csv")
grad20spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/20spr.csv")
#AY-18-19
grad18sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/18sum.csv")
grad18f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/18f.csv")
grad19spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/19spr.csv")
#AY17-18
grad17sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/17sum.csv")
grad17f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/17f.csv")
grad18spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/18spr.csv")
#AY16-17
grad16sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/16sum.csv")
grad16f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/16f.csv")
grad17spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/17spr.csv")
#merge
ipeds.complete16_crt<-
  join_all(list(grad21sum,grad22spr,grad21f,
                grad20sum,grad21spr,grad20f,
                grad19sum,grad20spr,grad19f,
                grad18sum,grad19spr,grad18f,
                grad17sum,grad18spr,grad17f,
                grad16sum,grad17spr,grad16f),
           type="full",match="first")%>%
  select(people_code_id,program,degree,major,graduation_date,Reporting_Ethnicity,gender)%>%
  dplyr::rename(PCID=people_code_id,level=program,gradd=graduation_date,race=Reporting_Ethnicity)
#remove
rm(grad21sum,grad22spr,grad21f,
   grad20sum,grad21spr,grad20f,
   grad19f,grad19sum,grad20spr,
   grad18f,grad18sum,grad19spr,
   grad17sum,grad18spr,grad17f,
   grad16sum,grad17spr,grad16f)

#####reformat date#####
class(ipeds.complete16_crt$gradd)#it's character
#convert the mdy formated character to date format
ipeds.complete16_crt$gradd<-mdy_hms(ipeds.complete16_crt$gradd)
class(ipeds.complete16_crt$gradd)#now it's date

#save merged data
write_xlsx(ipeds.complete16_crt,"/Users/linlizhou/Documents/LASELL/data/completion/16-current.xlsx")
```

```{r refining ipeds.compeltes}
#########level: Graduate Students, Undergraduate Students######
ipeds.complete16_crt%>%group_by(level)%>%dplyr::count()
#recode level
ipeds.complete16_crt$level<-ipeds.complete16_crt$level%>%recode(GRAD="Graduate Students",Graduate="Graduate Students",UNDER="Undergraduate Students",Undergraduate="Undergraduate Students")
#remove non gd/ug
ipeds.complete16_crt<-ipeds.complete16_crt%>%filter(level=="Graduate Students" | level== "Undergraduate Students")
#check
ipeds.complete16_crt%>%group_by(level)%>%dplyr::count()#level only contains Graduate Students, Undergraduate Students now

#########degree########
ipeds.complete16_crt%>%group_by(degree)%>%dplyr::count()#20 degrees, seems alright

######major########
list<-ipeds.complete16_crt%>%group_by(major)%>%dplyr::count()

ipeds.complete16_crt$major<-str_trim(ipeds.complete16_crt$major)#remove space at the end of major values
ipeds.complete16_crt$major<-ipeds.complete16_crt$major%>%
  recode(`Athletic Training MSAT`="Athletic Training",
         `Business Administration 2`="Business Administration",
         `Elementary Education MED`="Elementary Education",
         `Hospitality and Event Management`="Hospitality Management",
         `Initial Licensure MED`="Initial Licensure",
         `Initial Licensure MD`="Initial Licensure",
         `SecEduc & Applied Math`="Secondary Education",
         `Elementary Education and Applied Math`="Elementary Education",
         `Secondary Education and Applied Math`="Secondary Education")

####mutate a school col#####
ipeds.complete16_crt<-ipeds.complete16_crt%>%mutate(school=case_when(
  major=="Accounting"~"School of Business",
major=="Applied Forensic Science"~"School of Health Sciences",
major=="Applied Mathematics"~"School of Health Sciences",
major=="Arts Management"~"School of Business",
major=="Athletic Training"~"School of Health Sciences",
major=="Biology"~"School of Health Sciences",
major=="Business Administration"~"School of Business",
major=="Business Management"~"School of Business",
major=="Communication"~"School of Communication & the Arts",
major=="Creative Writing GR"~"School of Communication & the Arts",
major=="Criminal Justice"~"School of Humanities, Education, Justice & Social Sciences",
major=="Curriculum, Leadership & Inclusion"~"School of Humanities, Education, Justice & Social Sciences",
major=="Cybersecurity"~"School of Health Sciences",
major=="Data Analytics"~"School of Health Sciences",
major=="Early Childhood Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="Elementary Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="English"~"School of Humanities, Education, Justice & Social Sciences",
major=="Entrepreneurship"~"School of Business",
major=="Environmental Studies"~"School of Health Sciences",
major=="Event Management"~"School of Business",
major=="Exercise Science"~"School of Health Sciences",
major=="Fashion and Retail Merchandising"~"School of Fashion",
major=="Fashion Communication & Promotion"~"School of Fashion",
major=="Fashion Design and Production"~"School of Fashion",
major=="Finance"~"School of Business",
major=="Fitness Management"~"School of Business",
major=="Global Engagement"~"School of Humanities, Education, Justice & Social Sciences",
major=="Global Studies"~"School of Humanities, Education, Justice & Social Sciences",
major=="Graphic Design"~"School of Communication & the Arts",
major=="Health Communication"~"School of Health Sciences",
major=="Health Science"~"School of Health Sciences",
major=="History"~"School of Humanities, Education, Justice & Social Sciences",
major=="Hospitality Management"~"School of Business",
major=="Human Resources Management"~"School of Business",
major=="Human Services"~"School of Humanities, Education, Justice & Social Sciences",
major=="Humanities"~"School of Humanities, Education, Justice & Social Sciences",
major=="IDS Curriculum & Instruction"~"School of Humanities, Education, Justice & Social Sciences",
major=="IDS Early Childhood Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="IDS Forensic Criminology"~"School of Health Sciences",
major=="IDS Individualized"~"?",
major=="IDS Studio Arts"~"School of Communication & the Arts",
major=="Information Technology"~"School of Health Sciences",
major=="Initial Licensure"~"School of Humanities, Education, Justice & Social Sciences",
major=="Integrated Marketing Communication"~"School of Business",
major=="International Business"~"School of Business",
major=="Law and Public Affairs"~"School of Humanities, Education, Justice & Social Sciences",
major=="Legal Studies"~"School of Humanities, Education, Justice & Social Sciences",
major=="Management"~"School of Business",
major=="Marketing"~"School of Business",
major=="Moderate Disabilities"~"School of Humanities, Education, Justice & Social Sciences",
major=="Non Profit Management"~"School of Business",
major=="Nutrition for Human Performance"~"School of Health Sciences",
major=="Professional Licensure MD"~"School of Humanities, Education, Justice & Social Sciences",
major=="Project Management"~"School of Business",
major=="Psychology"~"School of Humanities, Education, Justice & Social Sciences",
major=="Public Relations MS Concentration"~"School of Communication & the Arts",
major=="Rehabilitation Science"~"School of Health Sciences",
major=="Resort and Casino Management"~"School of Business",
major=="Secondary Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="Secondary Education and English"~"School of Humanities, Education, Justice & Social Sciences",
major=="Secondary Education and History"~"School of Humanities, Education, Justice & Social Sciences",
major=="Sociology"~"School of Humanities, Education, Justice & Social Sciences",
major=="Sport Leadership"~"School of Business",
major=="Sport Management"~"School of Business"
))

########gradd########
ipeds.complete16_crt%>%group_by(gradd)%>%dplyr::count()
ipeds.complete16_crt$gradd<-format(ipeds.complete16_crt$gradd, format = "%Y")#keep year only

######race########
ipeds.complete16_crt%>%group_by(race)%>%dplyr::count()
######gender########
ipeds.complete16_crt%>%group_by(gender)%>%dplyr::count()
ipeds.complete16_crt$gender<-ipeds.complete16_crt$gender%>%recode(
  `F`="Female",
 `M`="Male",
  `U`="Unknown"
)

#save cleaned data
write_xlsx(ipeds.complete16_crt,"/Users/linlizhou/Documents/LASELL/data/completion/16-current.xlsx")
```



```{r archive codes}
###########################2021 fall ipeds.complete
#check which sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2021IPEDScompletions.xlsx")
#read data
#ipeds.complete21f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2021IPEDScompletions.xlsx",sheet = "Degrees - Combined")
#select useful cols and rename (prep for merge)
#ipeds.complete21f<-ipeds.complete21f%>%select(textbox41,textbox14,DEGREE,major,`Grad Date`)%>%dplyr::rename(PCID=textbox41,level=textbox14,degree=DEGREE,gradd=`Grad Date`)
#check names - prep for merge
#names(ipeds.complete21f)#do not have race and gender in raw data

############################2020 fall ipeds.complete#
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2020Merged Completions.xlsx")
#read data
#ipeds.complete20f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2020Merged Completions.xlsx",sheet = "Merged")
#select useful cols and rename (prep for merge)
#ipeds.complete20f<-ipeds.complete20f%>% select(`People Code ID`,Program,Degree,Curriculum,GradDate,Race,Gender) %>% 
 # dplyr::rename(PCID=`People Code ID`, level=Program, degree=Degree, major=Curriculum, gradd=GradDate, race=Race, gender=Gender)
#check names - prep for merge
#names(ipeds.complete20f)#keep a cip description for later use

############################2019 fall ipeds.complete
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2019Merged Completions.xlsm")
#read data
#ipeds.complete19f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2019Merged Completions.xlsm",sheet = "AllMerged")
#select useful cols and rename (prep for merge)
#ipeds.complete19f<-ipeds.complete19f%>%select(people_code_id,program,degree,curriculum,graduation_date,Race,gender)%>%dplyr::rename(PCID=people_code_id,level=program,major=curriculum,gradd=graduation_date,race=Race)
#check names - prep for merge
#names(ipeds.complete19f)

############################2018 fall ipeds.complete
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2018ipedsFComp_2017grad.clean.xlsx")
#read data
#ipeds.complete18f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2018ipedsFComp_2017grad.clean.xlsx")
#select useful cols and rename (prep for merge)
#ipeds.complete18f<-ipeds.complete18f%>%select(people_code_id,program,degree,curriculum,graduation_date,Race,gender)%>%
#  dplyr::rename(PCID=people_code_id,level=program,major=curriculum,gradd=graduation_date,race=Race)
#check names - prep for merge
#names(ipeds.complete18f)

############################2017 fall ipeds.complete
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2017ipedsFComp_2016grad.xlsx")
#read data
#ipeds.complete17f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2017ipedsFComp_2016grad.xlsx",sheet = "Merged_ALL")
#select useful cols and rename (prep for merge)
#ipeds.complete17f<-ipeds.complete17f%>%select(`People Code ID`,Program,Degree,Curriculum,`Graduation Date`,Race,Gender)%>%dplyr::rename(PCID=`People Code ID`,level=Program,degree=Degree,major=Curriculum,gradd=`Graduation Date`,race=Race,gender=Gender)
#check names - prep for merge
#names(ipeds.complete17f)
```

```{r explore merging functions}
#########################explore the different functions using 17-20f data
#rbind needs col of same length
#ncol(ipeds.complete17f)
#ncol(ipeds.complete18f)
#ncol(ipeds.complete19f)
#ncol(ipeds.complete20f)
#rbind
#ipeds.complete<-rbind(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f)#2421 observations
#exactly the same with adding all rows
#nrow(ipeds.complete17f)+nrow(ipeds.complete18f)+nrow(ipeds.complete19f)+nrow(ipeds.complete20f)#2421 observations

#rbind is the same with join by all matched cols
#ipeds.complete<-join_all(list(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f),type="full",match="first")#2420 observations; closest to rbind

#by=PCID limit to merge (turn into one) if find PCID in other dataset; match=first, only takes care of first match
#ipeds.complete<-join_all(list(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f),by="PCID",type="full",match="first")#2368 observations
#by=PCID limit to (turn into one) if find PCID in other dataset; match = all merge create a copy for all match
#ipeds.complete<-join_all(list(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f),by="PCID",type="full",match="all")#2379 observations
```


```{r archive cleaning codes}
#################################################################
######################archive codes for cleaning "degree" values###################
#################################################################
#check conc (invalid code in degree)
#ipeds.complete18f%>%group_by(degree)%>%count()#here is where conc exists
#list all curriculum under conc
#ipeds.complete18f%>%filter(degree=="CONC")%>%group_by(curriculum)%>%count()

#replace conc with the correct degree by looking the student up in powercampus
##powercampus lookup results show that we need to replace all CONC with MSM expect HSGJ as MSCJ
###replace HSGJ with MSCJ
#ipeds.complete18f[ipeds.complete18f$curriculum=="HSGJ",11]<-"MSCJ"#no headers/var names anymore so must use 11 as index
#check
#ipeds.complete18f%>%filter(degree=="CONC")%>%group_by(curriculum)%>%count()#no more hsgj
###replace all other CONC with MSM
#ipeds.complete18f[ipeds.complete18f$degree=="CONC",11]<-"MSM"
#check
#ipeds.complete18f%>%group_by(degree)%>%count()#no more conc


#check trk (invalid code in degree)
#ipeds.complete18f%>%filter(degree=="TRK")%>%group_by(curriculum)%>%count()
#lookedup in powercampus, replace all INLICM in TRK as MEDMD
#ipeds.complete18f[ipeds.complete18f$curriculum=="INLICM",11]<-"MEDMD"
#check
#ipeds.complete18f%>%filter(degree=="TRK")%>%group_by(curriculum)%>%count()#no more INLICM
#lookedup in powercampus, replace all PRLICM in TRK as MEDMD
#ipeds.complete18f[ipeds.complete18f$curriculum=="PRLICM",11]<-"MEDMD"
#check
#ipeds.complete18f%>%filter(degree=="TRK")%>%group_by(curriculum)%>%count()#no more prlicm
#lookedup in powercampus, replace INLICE as MEDEL
#ipeds.complete18f[ipeds.complete18f$curriculum=="INLICE",11]<-"MEDEL"
#check
#ipeds.complete18f%>%group_by(degree)%>%count()#no more TRK
```


# IPEDS Completions (due 2022 Oct 19)

#complete file: august 21  december 21 may 22 jan 22

```{r load data without NA cols}
rgs.cp<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Final List of Graduates By Date Range-Including Certs From Registrar.xlsx",skip = 6)%>%#header on row 7
              janitor::remove_empty(c("rows", "cols"))%>%#remove all-NA, inlcuding headers, rows/cols
              rename(ppid=`People Code ID`)

#remove all-NA cols: sum each col's # of NA rows, as long as not all rows are NA then select them 
rgs.cp <- rgs.cp[ , colSums(is.na(rgs.cp)) < nrow(rgs.cp)] # all rows of selected cols
rgs.cp <- rgs.cp%>%select(-...8)#remove another NA col that has one removable character value
rgs.cp <- rgs.cp[1:(nrow(rgs.cp)-2),]#remove the last two rows that are summarative total info and NAs

#explore: lapply(rgs.cp, unique)
#valuable vars:
##program GRAD/UNDER; Major; cip code (28 types)
##graduation date (4 types); Cohort 497 NA=matric date; 
rgs.cp%>%count(`Graduation Date`)
##transfer
#save
write.xlsx(rgs.cp,"/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Final List of Graduates By Date Range-Including Certs From Registrar_clean.xlsx")
```




















